# Generated by Django 5.0 on 2023-12-18 14:08

import django.db.models.deletion
import helpers.media_upload
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=helpers.media_upload.upload_restaurant)),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('rate', models.FloatField(default=0)),
                ('prepare_time', models.FloatField(blank=True, null=True)),
                ('calories', models.FloatField(blank=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, upload_to=helpers.media_upload.upload_pizza_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='pizza.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('rate', models.FloatField(default=0)),
                ('prepare_time', models.FloatField(blank=True, null=True)),
                ('calories', models.FloatField(blank=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=helpers.media_upload.upload_burger_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burger', to='pizza.restaurant')),
            ],
        ),
    ]
